export const REFRESH_TOKEN_ATTEMPT = "REFRESH_TOKEN_ATTEMPT";
export const REFRESH_TOKEN_FAIL = "REFRESH_TOKEN_FAIL";
export const REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS";

export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const LOGIN_USER_ATTEMPT = "LOGIN_USER_ATTEMPT";
export const LOGOUT_USER = "LOGOUT_USER";

export const CREATE_TASK_ATTEMPT = "TASK_CREATE_ATTEMPT";
export const CREATE_TASK_SUCCESS = "TASK_CREATE_SUCCESS";
export const CREATE_TASK_FAIL = "TASK_CREATE_FAIL";

export const DELETE_TASK_VISUALLY = "DELETE_TASK_VISUALLY";
export const DELETE_TASK_ATTEMPT = "DELETE_TASK_ATTEMPT";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_TASK_FAIL = "DELETE_TASK_FAIL";

export const UPDATE_TASK_VISUALLY = "UPDATE_TASK_VISUALLY";
export const UPDATE_TASK_ATTEMPT = "UPDATE_TASK_ATTEMPT";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
export const UPDATE_TASK_FAIL = "UPDATE_TASK_FAIL";

export const FETCH_TASKS_ATTEMPT = "FETCH_TASKS_ATTEMPT";
export const FETCH_TASKS_SUCCESS = "FETCH_TASKS_SUCCESS";
export const FETCH_TASKS_FAIL = "FETCH_TASKS_FAIL";

export const FETCH_PROJECTS_ATTEMPT = "FETCH_PROJECTS_ATTEMPT";
export const FETCH_PROJECTS_SUCCESS = "FETCH_PROJECTS_SUCCESS";
export const FETCH_PROJECTS_FAIL = "FETCH_PROJECTS_FAIL";

export const FETCH_TAGS_ATTEMPT = "FETCH_TAGS_ATTEMPT";
export const FETCH_TAGS_SUCCESS = "FETCH_TAGS_SUCCESS";
export const FETCH_TAGS_FAIL = "FETCH_TAGS_FAIL";


