export const REFRESH_TOKEN_ATTEMPT = "REFRESH_TOKEN_ATTEMPT";
export const REFRESH_TOKEN_FAIL = "REFRESH_TOKEN_FAIL";
export const REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS";

export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const LOGIN_USER_ATTEMPT = "LOGIN_USER_ATTEMPT";
export const LOGOUT_USER = "LOGOUT_USER";
export const CLEAN_USER_MESSAGE = "CLEAN_USER_MESSAGE";
///////////////////////////////////////////////////
export const CREATE_TASK_ATTEMPT = "TASK_CREATE_ATTEMPT";
export const CREATE_TASK_SUCCESS = "TASK_CREATE_SUCCESS";
export const CREATE_TASK_FAIL = "TASK_CREATE_FAIL";

export const DELETE_TASK_VISUALLY = "DELETE_TASK_VISUALLY";
export const DELETE_TASK_ATTEMPT = "DELETE_TASK_ATTEMPT";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_TASK_FAIL = "DELETE_TASK_FAIL";

export const UPDATE_TASK_VISUALLY = "UPDATE_TASK_VISUALLY";
export const UPDATE_TASK_ATTEMPT = "UPDATE_TASK_ATTEMPT";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
export const UPDATE_TASK_FAIL = "UPDATE_TASK_FAIL";

export const FETCH_TASK_ATTEMPT = "FETCH_TASK_ATTEMPT";
export const FETCH_TASK_SUCCESS = "FETCH_TASK_SUCCESS";
export const FETCH_TASK_FAIL = "FETCH_TASK_FAIL";

export const FETCH_TASKS_ATTEMPT = "FETCH_TASKS_ATTEMPT";
export const FETCH_TASKS_SUCCESS = "FETCH_TASKS_SUCCESS";
export const FETCH_TASKS_FAIL = "FETCH_TASKS_FAIL";

export const FETCH_DATES_ATTEMPT = "FETCH_DATES_ATTEMPT";
export const FETCH_DATES_SUCCESS = "FETCH_DATES_SUCCESS";
export const FETCH_DATES_FAIL = "FETCH_DATES_FAIL";

export const CLEAN_TASK_MESSAGE = "CLEAN_TASK_MESSAGE";
///////////////////////////////////////////////////
export const CREATE_PROJECT_ATTEMPT = "CREATE_PROJECT_ATTEMPT";
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_FAIL = "CREATE_PROJECT_FAIL";

export const FETCH_PROJECTS_ATTEMPT = "FETCH_PROJECTS_ATTEMPT";
export const FETCH_PROJECTS_SUCCESS = "FETCH_PROJECTS_SUCCESS";
export const FETCH_PROJECTS_FAIL = "FETCH_PROJECTS_FAIL";

export const FETCH_PROJECT_ATTEMPT = "FETCH_PROJECT_ATTEMPT";
export const FETCH_PROJECT_SUCCESS = "FETCH_PROJECT_SUCCESS";
export const FETCH_PROJECT_FAIL = "FETCH_PROJECT_FAIL";

export const DELETE_PROJECT_ATTEMPT = "DELETE_PROJECT_ATTEMPT";
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
export const DELETE_PROJECT_FAIL = "DELETE_PROJECT_FAIL";

export const UPDATE_PROJECT_VISUALLY = "UPDATE_PROJECT_VISUALLY";
export const UPDATE_PROJECT_ATTEMPT = "UPDATE_PROJECT_ATTEMPT";
export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS";
export const UPDATE_PROJECT_FAIL = "UPDATE_PROJECT_FAIL";

export const CLEAN_PROJECT_MESSAGE = "CLEAN_PROJECT_MESSAGE";
//////////////////////////////////////////////////
export const FETCH_TAGS_ATTEMPT = "FETCH_TAGS_ATTEMPT";
export const FETCH_TAGS_SUCCESS = "FETCH_TAGS_SUCCESS";
export const FETCH_TAGS_FAIL = "FETCH_TAGS_FAIL";
export const CLEAN_TAG_MESSAGE = "CLEAN_TAG_MESSAGE";
//////////////////////////////////////////////////

