/**Ejemplo de uso :
 * lang[config.lang].desc_placeholder_chrono_mode
 */
const lang = {
    ES: { 
        desc_placeholder_chrono_mode: "¿En qué vas a trabajar?",
        desc_placeholder_manual_mode: "¿En qué has estado trabajando?",
        hover_chrono_mode: "Modo cronómetro",
        hover_manual_mode: "Modo manual",
        hover_stop_chrono: "Parar cuenta y borrar tarea",
        err_end_hour_before: "La hora de finalización debe ser posterior a la de inicio.",
        err_hour_format: "Formato de hora no válido. Debe ser del tipo HH:MM.",
        aditional_menu_opt_delete: "Borrar",
        aditional_menu_opt_duply: "Duplicar",
        aditional_menu_opt_change_date: "Fecha",
        project_section_title: "Proyectos",
        dashboard_section_title: "Tablero",
        project_detail_section_title: "Proyecto",
        profile: "Perfil",
        btn_new_project: "Nuevo proyecto",
        btn_save_changes: "Guardar cambios",
        btn_delete: "¿Borrar?",
        project_name_placeholder: "Nombre del proyecto...",
        btn_cancel: "Cancelar",
        btn_confirm_delete: "Si, borrar",
        title_delete_project_modal: "¿Desea borrar el proyecto?",
        members_title: "Miembros",
        delete_project_member: "Eliminar miembro del proyecto",
        add_member_placeholder: "Añadir miembros al proyecto...",
        menu_timer: "Temporizador",
        menu_dashboard: "Tablero",
        menu_reports: "Informes",
        menu_tags: "Etiquetas",
        menu_projects: "Proyectos",
        menu_users: "Usuarios",
        menu_config: "Configuración",
        tag_section_title: "Etiquetas",
        btn_new_tag: "Nueva etiqueta",
        btn_update_tag: "Modificar etiqueta",
        btn_delete_tag: "Eliminar etiqueta",
        tag_name_placeholder: "Nombre de la etiqueta...",
        btn_title_delete_tag: "Borrar etiqueta",
        btn_title_update_tag: "Modificar etiqueta",
        th_project_name: "Nombre",
        th_project_created: "Fecha",
        th_project_hours: "Horas",
        th_project_tasks: "Tareas",
        project_data_title: "Datos de proyecto",
        project_tasks_title: "Tareas de proyecto",
        project_owner: "Propietario",
        project_hours: "Horas",
        project_creation: "Creación",
        dashboard_date_dropdown_title: "Intervalo de tiempo",
        date_today: "Hoy",
        date_this_week: "Esta semana",
        date_this_month: "Este mes",
        date_this_year: "Este año",
        date_yesterday: "Ayer",
        date_last_week: "Semana pasada",
        date_last_month: "Mes pasado",
        date_last_year: "Año pasado",
        date_custom: "Intervalo personalizado",
        time_units_days: "Dias",
        time_units_months: "Meses"
    }
};

export default lang;