/**Ejemplo de uso :
 * lang[config.lang].desc_placeholder_chrono_mode
 */
const lang = {
    ES: {
        desc_placeholder_chrono_mode: "¿En qué vas a trabajar?",
        desc_placeholder_manual_mode: "¿En qué has estado trabajando?",
        hover_chrono_mode: "Modo cronómetro",
        hover_manual_mode: "Modo manual",
        hover_stop_chrono: "Parar cuenta y borrar tarea",
        hover_create_disabled: "Debes escribir una descripción",
        err_end_hour_before: "La hora de finalización debe ser posterior a la de inicio.",
        err_hour_format: "Formato de hora no válido. Debe ser del tipo HH:MM.",
        aditional_menu_opt_delete: "Borrar",
        aditional_menu_opt_duply: "Duplicar",
        aditional_menu_opt_change_date: "Fecha",
        project_section_title: "Proyectos",
        dashboard_section_title: "Tablero",
        project_detail_section_title: "Proyecto",
        profile_section_title: "Perfil",
        profile: "Perfil",
        user_email_input: "Email",
        user_first_name_input: "Nombre",
        user_last_name_input: "Apellidos",
        user_avatar_input: "Modificar avatar",
        user_creation: "Fecha de registro",
        user_update: "Fecha última modificación",
        user_data_title: "Datos de usuario",
        user_email_placeholder: "Email de usuario",
        user_first_name_placeholder: "Nombre de usuario",
        user_last_name_placeholder: "Apellidos de usuario",
        title_delete_user_modal: "¿Desea borrar el usuario?",
        login_section_h1: "Iniciar sesión",
        login_section_btn_login: "Login",
        login_section_btn_signup: "Nuevo usuario",
        login_section_email_input: "Email",
        login_section_password_input: "Contraseña",
        login_section_email_placeholder: "Email",
        login_section_password_placeholder: "Contraseña",
        login_section_btn_login_disabled_title: "Rellena todos los campos del formulario correctamente",
        signup_section_h1: "Nuevo usuario",
        signup_section_h2: "Una vez completado el registro un administrador deberá activar tu cuenta antes de poder acceder a ella.",
        signup_section_btn_signup: "Registrar",
        signup_section_email_input: "Email",
        signup_section_password_input: "Contraseña",
        signup_section_repeat_password_input: "Repite contraseña",
        signup_section_email_placeholder: "Email",
        signup_section_password_placeholder: "Contraseña",
        signup_section_repeat_password_placeholder: "Repite contraseña",
        signup_section_i_already_have_an_account: "¿Ya tienes una cuenta?, haz click ",
        signup_section_btn_signup_disabled_title: "Rellena todos los campos del formulario correctamente",
        signup_section_here: "Aquí",
        btn_new_project: "Nuevo proyecto",
        btn_title_delete_project: "Borrar proyecto",
        btn_title_save_project: "Salvar cambios en proyecto",
        btn_title_delete_user: "Borrar usuario",
        btn_title_save_user: "Salvar cambios en usuario",
        btn_save_changes: "Guardar cambios",
        btn_delete: "¿Borrar?",
        project_name_placeholder: "Nombre del proyecto...",
        btn_cancel: "Cancelar",
        btn_confirm_delete: "Si, borrar",
        title_delete_project_modal: "¿Desea borrar el proyecto?",
        members_title: "Miembros",
        delete_project_member: "Eliminar miembro del proyecto",
        add_member_placeholder: "Añadir miembros al proyecto...",
        menu_timer: "Temporizador",
        menu_dashboard: "Tablero",
        menu_reports: "Informes",
        menu_tags: "Etiquetas",
        menu_projects: "Proyectos",
        menu_users: "Usuarios",
        menu_config: "Configuración",
        tag_section_title: "Etiquetas",
        user_section_title: "Usuarios",
        btn_new_tag: "Nueva etiqueta",
        btn_update_tag: "Modificar etiqueta",
        btn_delete_tag: "Eliminar etiqueta",
        tag_name_placeholder: "Nombre de la etiqueta...",
        btn_title_delete_tag: "Borrar etiqueta",
        btn_title_update_tag: "Modificar etiqueta",
        th_user_email: "Email",
        th_user_created: "Registro",
        th_user_first_name: "Nombre",
        th_user_last_name: "Apellidos",
        th_project_name: "Nombre",
        th_project_created: "Fecha",
        th_project_hours: "Horas",
        th_project_tasks: "Tareas",
        project_data_title: "Datos de proyecto",
        project_tasks_title: "Tareas de proyecto",
        project_owner: "Propietario",
        project_hours: "Horas imputadas",
        project_creation: "Creación",
        dashboard_date_dropdown_title: "Intervalo de tiempo",
        date_today: "Hoy",
        date_this_week: "Semana",
        date_this_month: "Mes",
        date_this_year: "Año",
        date_yesterday: "Ayer",
        date_last_week: "Semana pasada",
        date_last_month: "Mes pasado",
        date_last_year: "Año pasado",
        date_custom: "Intervalo personalizado",
        time_unit_days: "Dias",
        time_unit_months: "Meses",
        months_array: ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"],
        months_short_array: ["EN", "FB", "MZ", "AB", "MY", "JN", "JL", "AG", "SE", "OC", "NV", "DC"],
        weekdays_array: ["Domingo", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"],
        weekdays_short_array: ["D", "L", "M", "X", "J", "V", "S"],
        not_available: "No disponible",
        load_more: "Cargar más"
    }
};

export default lang;